title: Welcome
author: Ilia
email: ilia.panfilov95@gmail.com
description: Blog about studying in BMSTU

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
